version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - composer install
      - composer require annotations

  build:
    commands:
  post_build:
    commands:
      - php bin/console debug:router
