<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU52UvfH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU52UvfH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU52UvfH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU52UvfH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU52UvfH\App_KernelDevDebugContainer([
    'container.build_hash' => 'U52UvfH',
    'container.build_id' => 'fca83030',
    'container.build_time' => 1574514726,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU52UvfH');
